### ISSUE TITLE
Master branch build seg fault [Win 10]

### ISSUE THREAD

**Issue by SteveRussell33** [anlexmatos/FM-Delexander#2]
Adding module to empty patch causes Rack to crash.
```
Thread 15 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 8872.0x7dc]
0x000000000d1c33d8 in rack::engine::Param::getValue (this=0x12d1e8448) at ../../include/engine/Param.hpp:16
16                      return value;
(gdb) bt
#0  0x000000000d1c33d8 in rack::engine::Param::getValue (this=0x12d1e8448) at ../../include/engine/Param.hpp:16
#1  Algomorph4::process (this=0x22fecf90, args=...) at src/Algomorph.cpp:340
#2  0x000000000049f347 in rack::engine::Engine_stepModules (threadId=0, that=<optimized out>, that=<optimized out>) at src/engine/Engine.cpp:269
#3  0x00000000004a1652 in rack::engine::Engine_step (that=0xca22ed0) at src/engine/Engine.cpp:346
#4  rack::engine::Engine_run (that=0xca22ed0) at src/engine/Engine.cpp:448
#5  operator() (__closure=<optimized out>) at src/engine/Engine.cpp:482
#6  std::__invoke_impl<void, rack::engine::Engine::start()::<lambda()> > (__f=...) at C:/msys64/mingw64/include/c++/10.2.0/bits/invoke.h:60
#7  std::__invoke<rack::engine::Engine::start()::<lambda()> > (__fn=...) at C:/msys64/mingw64/include/c++/10.2.0/bits/invoke.h:95
#8  std::thread::_Invoker<std::tuple<rack::engine::Engine::start()::<lambda()> > >::_M_invoke<0> (this=<optimized out>)
    at C:/msys64/mingw64/include/c++/10.2.0/thread:264
#9  std::thread::_Invoker<std::tuple<rack::engine::Engine::start()::<lambda()> > >::operator() (this=<optimized out>)
    at C:/msys64/mingw64/include/c++/10.2.0/thread:271
#10 std::thread::_State_impl<std::thread::_Invoker<std::tuple<rack::engine::Engine::start()::<lambda()> > > >::_M_run(void) (this=<optimized out>)
    at C:/msys64/mingw64/include/c++/10.2.0/thread:215
#11 0x000000006fd39d01 in ?? () from /c/Program Files/VCV/v1/libstdc++-6.dll
#12 0x0000000064944b42 in ?? () from /c/Program Files/VCV/v1/libwinpthread-1.dll
#13 0x00007ff89b60b04a in msvcrt!_beginthreadex () from /c/WINDOWS/System32/msvcrt.dll
#14 0x00007ff89b60b11c in msvcrt!_endthreadex () from /c/WINDOWS/System32/msvcrt.dll
#15 0x00007ff89b347bd4 in KERNEL32!BaseThreadInitThunk () from /c/WINDOWS/System32/KERNEL32.DLL
#16 0x00007ff89c74ce51 in ntdll!RtlUserThreadStart () from /c/WINDOWS/SYSTEM32/ntdll.dll
#17 0x0000000000000000 in ?? ()
```

**Comment by SteveRussell33** [comment]
Confirmed fixed as of https://github.com/anlexmatos/FM-Delexander/commit/1e66a8dc8efa60cd93970bb4d1725d97b3161263
